app = "3foodskingdom"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[checks.status]
grace_period = "5s"
interval = "10s"
method = "GET"
path = "/up"
port = 3000
protocol = "http"
timeout = "2s"
tls_skip_verify = false
type = "http"

  [checks.status.headers]
  X-Forwarded-Proto = "https"

[deploy]
release_command = "/rails/bin/rails db:prepare"

[env]
RAILS_ENV = "production"
# 他の環境変数も必要に応じて追加

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
auto_stop_machines = true
min_machines_running = 0
processes = ["app"]

[[statics]]
guest_path = "/rails/public"
url_prefix = "/"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
